Update schedule-w-matrix.yml

diff --git a/.github/workflows/schedule-w-matrix.yml b/.github/workflows/schedule-w-matrix.yml
--- a/.github/workflows/schedule-w-matrix.yml
+++ b/.github/workflows/schedule-w-matrix.yml
@@ -60,6 +60,21 @@ jobs:
         run: |
           echo "pwd:"
           pwd
+          
+          if [[ "${{ matrix.issue_template }}" == "do-not-use" ]]
+          then
+            echo "For now (11-15-2025), the 'do-not-use' matrix template option should just fail if it's encountered. Failing this job."
+            exit 1
+          fi
+          echo "github.event = ${{ github.event }}"
+          
+          if [[ "${{ github.event }}"  == "workflow_dispatch" && "${{ matrix.issue_template }}" == "do-not-use-2" ]]
+          then
+            echo "This job uses 'do-not-use-2' as a value for matrix.issue_template. This doesn't point to a valid template."
+            echo "This shouldn't be activated when fired off by a schedule. It will activate AND fail if called via workflow_dispatch."
+            exit 1
+          fi
+          
           echo "This issue template (ISS_TEMP) for this job is $ISS_TEMP."
           echo "This step should get the issue template from above, and write its contents to env"
           template_text=$(cat .github/ISSUE_TEMPLATE/$ISS_TEMP)
@@ -79,20 +94,6 @@ jobs:
       - name: Create Issue Using Template
         run: |
           echo "About to make a new issue using an issue template (${{ matrix.issue_template }})."
-          
-          if [[ "${{ matrix.issue_template }}" == "do-not-use" ]]
-          then
-            echo "For now (11-15-2025), the 'do-not-use' matrix template option should just fail if it's encountered. Failing this job."
-            exit 1
-          fi
-          echo "github.event = ${{ github.event }}"
-          
-          if [[ "${{ github.event }}"  == "workflow_dispatch" && "${{ matrix.issue_template }}" == "do-not-use-2" ]]
-          then
-            echo "This job uses 'do-not-use-2' as a value for matrix.issue_template. This doesn't point to a valid template."
-            echo "This shouldn't be activated when fired off by a schedule. It will activate AND fail if called via workflow_dispatch."
-            exit 1
-          fi
 
           if [[ "${{ github.event.inputs.verbose }}" == "true" ]]
           then
